import esbuild from "esbuild";
import process from "process";
import fs from "fs/promises";
import { watch } from "fs";
import path from "path";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Function to ensure directory exists
async function ensureDir(dir) {
    try {
        await fs.access(dir);
    } catch {
        await fs.mkdir(dir, { recursive: true });
    }
}

// Function to copy styles to dist
async function copyStyles() {
    try {
        // Ensure assets directory exists
        await ensureDir('dist/assets');
        
        // Copy styles to assets directory
        await fs.copyFile('src/styles/styles.css', 'dist/assets/styles.css');
        console.log('CSS file copied successfully');
    } catch (err) {
        console.error('Error copying CSS file:', err);
    }
}

const buildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: ['obsidian'],
    format: 'cjs',
    target: 'es2016',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'dist/main.js',
};

if (process.argv[2] === '--watch') {
    // Watch mode
    buildOptions.watch = {
        onRebuild(error, result) {
            if (error) console.error('watch build failed:', error);
            else {
                console.log('watch build succeeded');
                copyStyles();
            }
        },
    };

    // Build with watch mode
    esbuild.build(buildOptions).then(result => {
        copyStyles();
        console.log('watching...');
    });
} else {
    // Build once
    esbuild.build(buildOptions).then(() => {
        copyStyles();
    });
}